API_SECRET = 'eEfglHVB2FvtzWDxqBTfET0wU9ZdQmRKYV0LhblhY7vcZUk0XORUaDo2mHKVG3Pv'
API_KEY = 'CkVbWa8VuCoDa6jmSmqtUtvLNnPReu7IPPoyM34utHnoZVjEpvksUnptgpWKCWBq'
MONGO_USER = "crypto"
MONGO_PASSWORD = "mongopass220694"