---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: bin-listener
  namespace: binancelistener
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bin-listener
  template:
    metadata:
      labels:
        app: bin-listener
    spec:
      containers:
      - name: bin-listener
        image: godiisd/binance-listener:0.0.1
        ports:
        - name: http
          containerPort: 5000
        env:
        - name: API_KEY
          valueFrom:
            secretKeyRef:
              name: creds
              key: api-key
        - name: API_SECRET
          valueFrom:
            secretKeyRef:
              name: creds
              key: api-secret
        - name: MONGODB_HOSTNAME
          value: mongodb-697b6f857c-fwnhn.mongodb
        - name: MONGODB_PORT
          value: "27017"
        - name: MONGODB_DATABASE
          value: inventory
        resources:
          limits:
            cpu: 200m
            memory: 256Mi
          requests:
            cpu: 100m
            memory: 128Mi